spring:     
    datasource:
        url: jdbc:mysql://localhost:3306/activitiflow?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
        username: root
        password: 123456
        drvier-class-name: com.mysql.jdbc.Driver
        type: com.alibaba.druid.pool.DruidDataSource
        
    activiti:
        database-schema-update: true
        history-level: full
        db-history-used: true
                
    thymeleaf:
        mode: HTML
        encoding: utf-8
        cache: false  #热加载
        
    mvc:
        static-path-pattern: /static/**    